package test;

import java.io.InputStream;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Test;

import com.ibm.integration.test.v1.NodeSpy;
import com.ibm.integration.test.v1.SpyObjectReference;
import com.ibm.integration.test.v1.TestMessageAssembly;
import com.ibm.integration.test.v1.TestSetup;
import com.ibm.integration.test.v1.exception.TestException;

import static com.ibm.integration.test.v1.Matchers.*;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class ExampleAppUsingJCN_ExampleAppUsingJCN_Java_Compute_0001_Test {

	/*
	 * ExampleAppUsingJCN_ExampleAppUsingJCN_Java_Compute_0001_Test
	 * Test generated by IBM App Connect Enterprise Toolkit 12.0.8.0 on May 26, 2023 1:52:00 PM
	 */

	@AfterEach
	public void cleanupTest() throws TestException {
		// Ensure any mocks created by a test are cleared after the test runs 
		TestSetup.restoreAllMocks();
	}

	@Test
	public void ExampleAppUsingJCN_ExampleAppUsingJCN_Java_Compute_TestCase_001() throws TestException {

		// Define the SpyObjectReference
		SpyObjectReference nodeReference = new SpyObjectReference().application("ExampleAppUsingJCN")
				.messageFlow("ExampleAppUsingJCN").node("Java Compute");

		// Initialise a NodeSpy
		NodeSpy nodeSpy = new NodeSpy(nodeReference);

		// Declare a new TestMessageAssembly object for the message being sent into the node
		TestMessageAssembly inputMessageAssembly = new TestMessageAssembly();

		// Create a Message Assembly from the input data file
		try {
			String messageAssemblyPath = "/httpInput.mxml";
			InputStream messageStream = Thread.currentThread().getContextClassLoader()
					.getResourceAsStream(messageAssemblyPath);
			if (messageStream == null) {
				throw new TestException("Unable to locate message assembly file: " + messageAssemblyPath);
			}
			inputMessageAssembly.buildFromRecordedMessageAssembly(messageStream);
		} catch (Exception ex) {
			throw new TestException("Failed to load input message", ex);
		}

		// Call the message flow node with the Message Assembly
		nodeSpy.evaluate(inputMessageAssembly, false, "in");

		// Assert the number of times that the node is called
		assertThat(nodeSpy, nodeCallCountIs(1));

		// Assert the terminal propagate count for the message
		assertThat(nodeSpy, terminalPropagateCountIs("out", 1));

		TestMessageAssembly actualMessageAssembly = null;
		// Get the TestMessageAssembly object for the actual propagated message
		actualMessageAssembly = nodeSpy.propagatedMessageAssembly("out", 1);
		assertEquals("ExampleUserDefinedPolicyProject",
				actualMessageAssembly.messagePath("XMLNSC.ResponseMessage.UserDefinedPolicyProject").getValueAsString());
	}

}
